# This is a config for E2B sandbox template.
# You can use template ID (uwjrc97qg8qfno0643qu) or template name (neurogranada) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("neurogranada") # Sync sandbox
# sandbox = await AsyncSandbox.create("neurogranada") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('neurogranada')

template_id = "uwjrc97qg8qfno0643qu"
dockerfile = "Dockerfile.sandbox"
template_name = "neurogranada"
start_cmd = "npm run dev --turbopack"
ready_cmd = 'curl -s -o /dev/null -w "%{http_code}" http://localhost:3000 | grep -q "200"'
cpu_count = 2
memory_mb = 2_048
team_id = "325cdb4d-008d-48a5-bd38-186c3b3159ca"
